### PR TITLE
Add GH action to automate running the experiments

### PR DESCRIPTION
**Pull request by jprinet**
Requires composite actions from:
- https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/45/files

### CODE REVIEW

**Comment by jprinet** [comment]
Back to draft to incorporate exp 5 before review

**Comment by jprinet** [comment]
PR is ready for review 👍

The objective is to be able to automatically run experiments 1, 2 and 3 on OSS projects.

There are 2 triggers:
- scheduled to run all experiments on all project once a week
- manual to run one or all experiments on a selected project

**Comment by bigdaz** [comment]
@jprinet Would it be useful to use the `gradle-build-action` to save/restore the Gradle User Home state for these jobs? This could speed up the jobs by avoiding things like recreating `generated-gradle-jars`, recompiling build scrips, etc.

Note that it's now recommended to [separate the "Setup Gradle" and "Run Gradle" steps in your workflow](https://github.com/gradle/gradle-build-action#use-the-action-to-setup-gradle). 

If necessary, it's easy to exclude `~/.gradle/caches/build-cache-1` from this process.

**Comment by jprinet** [comment]
> @jprinet Would it be useful to use the `gradle-build-action` to save/restore the Gradle User Home state for these jobs? This could speed up the jobs by avoiding things like recreating `generated-gradle-jars`, recompiling build scrips, etc.
> 
> Note that it's now recommended to [separate the "Setup Gradle" and "Run Gradle" steps in your workflow](https://github.com/gradle/gradle-build-action#use-the-action-to-setup-gradle).
> 
> If necessary, it's easy to exclude `~/.gradle/caches/build-cache-1` from this process.

To be honest, I'm divided on this one. Most experiments trying to fully build the project from scratch without sharing any data. It's a true point that we could save some time on all Gradle internals, but those jobs are long running anyway.

**Comment by bigdaz** [comment]
> Most experiments trying to fully build the project from scratch without sharing any data. 

Yes, but we don't ask users to delete their Gradle User Home before each experiment. This is effectively what you automation is doing. So all dependencies, Gradle wrappers, JDKs etc are re-downloaded, and local state is re-generated.

**Comment by jprinet** [comment]
> > Most experiments trying to fully build the project from scratch without sharing any data.
> 
> Yes, but we don't ask users to delete their Gradle User Home before each experiment. This is effectively what you automation is doing. So all dependencies, Gradle wrappers, JDKs etc are re-downloaded, and local state is re-generated.

Makes sense, let's reduce data transfer with your suggestion 👍
Will do excluding cache as you mentioned!

**Review by bigdaz — APPROVED** [review]
LGTM

**Comment by etiennestuder** [comment]
Thanks, @jprinet . I'll close the PR given we will go with separate workflows for each OSS project.

**Pull request closed without merging**
